/* eslint-disable */
/**
 * Auto-generated from agent-api.ts. Fully declarative spec.
 * Run: npx tsx scripts/generate-agent-api-spec.ts
 */

export interface ToolSpec {
  name: string;
  description: string;
  returns: string;
  params?: string;
  paramsType?: string;
  paramsSchema?: Record<string, unknown>;
}

export const TOOL_SPECS: ToolSpec[] = [
  { name: "bus.delete", description: "List all message buses.", returns: "\"Bus {mb_id} deleted.\"", params: "{ mb_id: string }", paramsType: "{ mb_id: string }", paramsSchema: {"type":"object","properties":{"mb_id":{"type":"string"}},"required":["mb_id"]} },
  { name: "bus.get_history", description: "List all message buses.", returns: "HistoryMessage[] — see Shared types", params: "{ bus_id: string; limit?: number; offset?: number }", paramsType: "{ bus_id: string; limit?: number; offset?: number }", paramsSchema: {"type":"object","properties":{"bus_id":{"type":"string"},"limit":{"type":"number"},"offset":{"type":"number"}},"required":["bus_id"]} },
  { name: "bus.list", description: "List all message buses.", returns: "BusEntry[] — see Shared types" },
  { name: "bus.set_properties", description: "List all message buses.", returns: "\"Properties set for {mb_id}.\"", params: "{\n        mb_id: string;\n        description?: string;\n        trust_level?: \"normal\" | \"root\";\n        is_banned?: boolean;\n      }", paramsType: "{\n        mb_id: string;\n        description?: string;\n        trust_level?: \"normal\" | \"root\";\n        is_banned?: boolean;\n      }", paramsSchema: {"type":"object","properties":{"mb_id":{"type":"string"},"description":{"type":"string"},"trust_level":{"type":"string","enum":["normal","root"]},"is_banned":{"type":"boolean"}},"required":["mb_id"]} },
  { name: "contacts.create", description: "List all message buses.", returns: "string — created id", params: "{\n        name: string;\n        identifier: string;\n        trust_level?: \"normal\" | \"root\";\n        bus_ids?: string[];\n        notes?: string;\n      }", paramsType: "{\n        name: string;\n        identifier: string;\n        trust_level?: \"normal\" | \"root\";\n        bus_ids?: string[];\n        notes?: string;\n      }", paramsSchema: {"type":"object","properties":{"name":{"type":"string"},"identifier":{"type":"string"},"trust_level":{"type":"string","enum":["normal","root"]},"bus_ids":{"type":"array","items":{"type":"string"}},"notes":{"type":"string"}},"required":["name","identifier"]} },
  { name: "contacts.delete", description: "List all message buses.", returns: "void", params: "{ id_or_identifier: string }", paramsType: "{ id_or_identifier: string }", paramsSchema: {"type":"object","properties":{"id_or_identifier":{"type":"string"}},"required":["id_or_identifier"]} },
  { name: "contacts.get", description: "List all message buses.", returns: "Contact | null — contact with notes", params: "{ id_or_identifier: string }", paramsType: "{ id_or_identifier: string }", paramsSchema: {"type":"object","properties":{"id_or_identifier":{"type":"string"}},"required":["id_or_identifier"]} },
  { name: "contacts.is_trusted", description: "List all message buses.", returns: "boolean", params: "{ bus_id: string; sender_email?: string }", paramsType: "{ bus_id: string; sender_email?: string }", paramsSchema: {"type":"object","properties":{"bus_id":{"type":"string"},"sender_email":{"type":"string"}},"required":["bus_id"]} },
  { name: "contacts.list", description: "List all message buses.", returns: "Contact[] — see Shared types" },
  { name: "contacts.search", description: "List all message buses.", returns: "Contact[] — filtered by name/notes", params: "{ query: string }", paramsType: "{ query: string }", paramsSchema: {"type":"object","properties":{"query":{"type":"string"}},"required":["query"]} },
  { name: "contacts.update", description: "List all message buses.", returns: "void", params: "{\n        id_or_identifier: string;\n        name?: string;\n        identifier?: string;\n        trust_level?: \"normal\" | \"root\";\n        bus_ids?: string[];\n        notes?: string;\n      }", paramsType: "{\n        id_or_identifier: string;\n        name?: string;\n        identifier?: string;\n        trust_level?: \"normal\" | \"root\";\n        bus_ids?: string[];\n        notes?: string;\n      }", paramsSchema: {"type":"object","properties":{"id_or_identifier":{"type":"string"},"name":{"type":"string"},"identifier":{"type":"string"},"trust_level":{"type":"string","enum":["normal","root"]},"bus_ids":{"type":"array","items":{"type":"string"}},"notes":{"type":"string"}},"required":["id_or_identifier"]} },
  { name: "get_datetime", description: "Get current ISO datetime.", returns: "string — ISO 8601 (e.g. \"2025-03-15T12:00:00.000Z\")" },
  { name: "mail.append", description: "Append message.", returns: "object — imapflow result", params: "path, content (required), flags?, idate? (optional)", paramsType: "{ path: string; content: string; flags?: string; idate?: string }", paramsSchema: {"type":"object","properties":{"path":{"type":"string"},"content":{"type":"string"},"flags":{"type":"string"},"idate":{"type":"string"}},"required":["path","content"]} },
  { name: "mail.connect", description: "Connect to IMAP.", returns: "\"Connected. Bus {busId} created. {n} message(s) loaded.\"", params: "host, port, user, pass (required), secure? (optional)", paramsType: "{\n        host: string;\n        port: number;\n        user: string;\n        pass: string;\n        secure?: boolean;\n      }", paramsSchema: {"type":"object","properties":{"host":{"type":"string"},"port":{"type":"number"},"user":{"type":"string"},"pass":{"type":"string"},"secure":{"type":"boolean"}},"required":["host","port","user","pass"]} },
  { name: "mail.disconnect", description: "Disconnect from IMAP.", returns: "\"Disconnected.\"" },
  { name: "mail.download", description: "Download attachment.", returns: "\"Saved to {absolute_path}\"", params: "range (required), part?, uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        part?: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"part":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range"]} },
  { name: "mail.fetch_all", description: "Fetch messages.", returns: "MailFetchMessage[] — see Shared types (envelope: date, subject, from, to, cc, bcc, messageId; flags; internalDate; size; source?; labels?; threadId?)", params: "range (required), query? (object or JSON string), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        query?: string | Record<string, unknown>;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"query":{"type":"string","description":"string | Record<string, unknown>"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range"]} },
  { name: "mail.fetch_one", description: "Fetch one message.", returns: "MailFetchMessage | null — see Shared types", params: "seq (required), query? (object or JSON string), uid?, mailbox? (optional)", paramsType: "{\n        seq: string;\n        query?: string | Record<string, unknown>;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"seq":{"type":"string"},"query":{"type":"string","description":"string | Record<string, unknown>"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["seq"]} },
  { name: "mail.get_quota", description: "Get quota.", returns: "IMAP GETQUOTA result", params: "path (required)", paramsType: "{ path: string }", paramsSchema: {"type":"object","properties":{"path":{"type":"string"}},"required":["path"]} },
  { name: "mail.list", description: "List mailboxes.", returns: "{ path: string; name: string; specialUse?: string[]; status?: { messages?: number; unseen?: number; uidNext?: number; uidValidity?: string; recent?: number; highestModseq?: string } }[]", params: "statusQuery? (optional)", paramsType: "{ statusQuery?: string }", paramsSchema: {"type":"object","properties":{"statusQuery":{"type":"string"}},"required":[]} },
  { name: "mail.list_tree", description: "List mailbox tree.", returns: "Nested tree from imapflow listTree()" },
  { name: "mail.mailbox_close", description: "Close mailbox.", returns: "\"Closed.\"" },
  { name: "mail.mailbox_create", description: "Create mailbox.", returns: "object — imapflow result", params: "path (required)", paramsType: "{ path: string }", paramsSchema: {"type":"object","properties":{"path":{"type":"string"}},"required":["path"]} },
  { name: "mail.mailbox_delete", description: "Delete mailbox.", returns: "\"Deleted.\"", params: "path (required)", paramsType: "{ path: string }", paramsSchema: {"type":"object","properties":{"path":{"type":"string"}},"required":["path"]} },
  { name: "mail.mailbox_open", description: "Open mailbox.", returns: "\"Opened {path}\"", params: "path (required), readOnly? (optional)", paramsType: "{ path: string; readOnly?: boolean }", paramsSchema: {"type":"object","properties":{"path":{"type":"string"},"readOnly":{"type":"boolean"}},"required":["path"]} },
  { name: "mail.mailbox_rename", description: "Rename mailbox.", returns: "\"Renamed.\"", params: "oldPath, newPath (required)", paramsType: "{ oldPath: string; newPath: string }", paramsSchema: {"type":"object","properties":{"oldPath":{"type":"string"},"newPath":{"type":"string"}},"required":["oldPath","newPath"]} },
  { name: "mail.mailbox_subscribe", description: "Subscribe to mailbox.", returns: "\"Subscribed.\"", params: "path (required)", paramsType: "{ path: string }", paramsSchema: {"type":"object","properties":{"path":{"type":"string"}},"required":["path"]} },
  { name: "mail.mailbox_unsubscribe", description: "Unsubscribe from mailbox.", returns: "\"Unsubscribed.\"", params: "path (required)", paramsType: "{ path: string }", paramsSchema: {"type":"object","properties":{"path":{"type":"string"}},"required":["path"]} },
  { name: "mail.message_copy", description: "Copy message(s).", returns: "object — imapflow result", params: "range, destination (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        destination: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"destination":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","destination"]} },
  { name: "mail.message_delete", description: "Delete message(s).", returns: "\"Deleted.\"", params: "range (required), uid?, mailbox? (optional)", paramsType: "{ range: string; uid?: boolean; mailbox?: string }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range"]} },
  { name: "mail.message_flags_add", description: "Add flags.", returns: "\"Done.\"", params: "range, flags (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        flags: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"flags":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","flags"]} },
  { name: "mail.message_flags_remove", description: "Remove flags.", returns: "\"Done.\"", params: "range, flags (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        flags: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"flags":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","flags"]} },
  { name: "mail.message_flags_set", description: "Set flags.", returns: "\"Done.\"", params: "range, flags (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        flags: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"flags":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","flags"]} },
  { name: "mail.message_labels_add", description: "Add labels.", returns: "\"Done.\"", params: "range, labels (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        labels: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"labels":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","labels"]} },
  { name: "mail.message_labels_remove", description: "Remove labels.", returns: "\"Done.\"", params: "range, labels (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        labels: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"labels":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","labels"]} },
  { name: "mail.message_labels_set", description: "Set labels.", returns: "\"Done.\"", params: "range, labels (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        labels: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"labels":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","labels"]} },
  { name: "mail.message_move", description: "Move message(s).", returns: "\"Moved.\"", params: "range, destination (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        destination: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"destination":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","destination"]} },
  { name: "mail.search", description: "Search messages.", returns: "number[] — UIDs", params: "query (required, object or JSON string), uid?, mailbox? (optional)", paramsType: "{ query: string | Record<string, unknown>; uid?: boolean; mailbox?: string }", paramsSchema: {"type":"object","properties":{"query":{"type":"string","description":"string | Record<string, unknown>"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["query"]} },
  { name: "mail.set_flag_color", description: "Set flag color.", returns: "\"Done.\"", params: "range, color (required), uid?, mailbox? (optional)", paramsType: "{\n        range: string;\n        color: string;\n        uid?: boolean;\n        mailbox?: string;\n      }", paramsSchema: {"type":"object","properties":{"range":{"type":"string"},"color":{"type":"string"},"uid":{"type":"boolean"},"mailbox":{"type":"string"}},"required":["range","color"]} },
  { name: "mail.status", description: "Get mailbox status.", returns: "{ path: string; ... } — status fields from query", params: "path (required), query? (optional)", paramsType: "{ path: string; query?: string }", paramsSchema: {"type":"object","properties":{"path":{"type":"string"},"query":{"type":"string"}},"required":["path"]} },
  { name: "passwords.delete", description: "Delete a password.", returns: "\"Password \\\"{id}\\\" deleted.\" (id = uuid or description)", params: "id (uuid or description)", paramsType: "{ id: string }", paramsSchema: {"type":"object","properties":{"id":{"type":"string"}},"required":["id"]} },
  { name: "passwords.get", description: "Get a password by uuid or description. For totp: returns OTP code by default; raw=true returns the seed.", returns: "string — For type=string: the value. For type=totp: OTP code (6 digits) by default; raw=true returns the seed. When not found: \"Password \\\"{id}\\\" not found.\" (id = uuid or description)", params: "id (uuid or description), raw? (optional)", paramsType: "{ id: string; raw?: boolean }", paramsSchema: {"type":"object","properties":{"id":{"type":"string"},"raw":{"type":"boolean"}},"required":["id"]} },
  { name: "passwords.list", description: "List passwords.", returns: "PasswordListEntry[] — see Shared types" },
  { name: "passwords.set", description: "Set a password.", returns: "\"Password set. uuid=\\\"{uuid}\\\"\"", params: "description (required), type (string|totp), value (required), force? (optional), uuid? (optional, for update)", paramsType: "{\n        description: string;\n        type: \"string\" | \"totp\";\n        value: string;\n        force?: boolean;\n        uuid?: string;\n      }", paramsSchema: {"type":"object","properties":{"description":{"type":"string"},"type":{"type":"string","enum":["string","totp"]},"value":{"type":"string"},"force":{"type":"boolean"},"uuid":{"type":"string"}},"required":["description","type","value"]} },
  { name: "schedule.add", description: "Delete a password.", returns: "\"Scheduled task \\\"{title}\\\" for {at} (id: {id}).\"", params: "id (uuid or description)", paramsType: "{ at: string; title: string; instructions: string }", paramsSchema: {"type":"object","properties":{"at":{"type":"string"},"title":{"type":"string"},"instructions":{"type":"string"}},"required":["at","title","instructions"]} },
  { name: "schedule.delete", description: "Delete a password.", returns: "\"Deleted scheduled task {task_id}.\"", params: "id (uuid or description)", paramsType: "{ task_id: string }", paramsSchema: {"type":"object","properties":{"task_id":{"type":"string"}},"required":["task_id"]} },
  { name: "schedule.list", description: "Delete a password.", returns: "ListTasksResult — see Shared types", params: "id (uuid or description)" },
  { name: "soul.get", description: "List all message buses.", returns: "string — SOUL.md content" },
  { name: "soul.set", description: "List all message buses.", returns: "void", params: "{ content: string }", paramsType: "{ content: string }", paramsSchema: {"type":"object","properties":{"content":{"type":"string"}},"required":["content"]} },
  { name: "task.finalize", description: "Delete a password.", returns: "\"Task finalized.\"", params: "id (uuid or description)", paramsType: "{ is_successful: boolean }", paramsSchema: {"type":"object","properties":{"is_successful":{"type":"boolean"}},"required":["is_successful"]} },
  { name: "task.start", description: "Delete a password.", returns: "\"Task started.\"", params: "id (uuid or description)", paramsType: "{ summary: string }", paramsSchema: {"type":"object","properties":{"summary":{"type":"string"}},"required":["summary"]} },
  { name: "telegram_search", description: "Resolve username to bus_id.", returns: "TelegramSearchResult — see Shared types", params: "username (required)", paramsType: "{ username: string }", paramsSchema: {"type":"object","properties":{"username":{"type":"string"}},"required":["username"]} },
  { name: "vm.kill", description: "Force-kill a VM. Shut down the VM with shutdown -h now (via vm_serial) before killing.", returns: "\"VM killed.\" | \"Error: ...\"", params: "vm_id (required)", paramsType: "{ vm_id: string }", paramsSchema: {"type":"object","properties":{"vm_id":{"type":"string"}},"required":["vm_id"]} },
  { name: "vm.power_on", description: "Power on a VM.", returns: "(non-setup: aborts eval, shows notice) | \"Error: ...\"", params: "vm_id (required)", paramsType: "{ vm_id: string }", paramsSchema: {"type":"object","properties":{"vm_id":{"type":"string"}},"required":["vm_id"]} }
];
